#!/bin/sh
#
# check_isr_storage - Show a popup giving the status of Pocket ISR storage
#
# Copyright (C) 2010 Carnegie Mellon University
#
# This program is free software; you can redistribute it and/or modify it
# under the terms of version 2 of the GNU General Public License as published
# by the Free Software Foundation.  A copy of the GNU General Public License
# should have been distributed along with this program in the file
# COPYING.
#
# This program is distributed in the hope that it will be useful, but
# WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY
# or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public License
# for more details.
#

ROOT=/home

detect() {
	if ! mountpoint -q $ROOT ; then
		echo "none"
	elif df -P $ROOT | grep -q scratch-home ; then
		echo "transient"
	else
		echo "persistent"
	fi
}

notify() {
	free_gb=$(($(df -P $ROOT | awk '!/Filesystem/ {print $4}') >> 20))
	case "$1" in
	transient)
		short="Using transient parcel storage"
		long="Found $free_gb GiB of transient parcel storage.  Parcel data will become inaccessible after the system is shut down."
		;;
	persistent)
		short="Using persistent parcel storage"
		long="Found persistent parcel storage with $free_gb GiB free.  Do not unplug the boot device until the system is shut down."
		;;
	none)
		notify-send -u critical -t 0 -c device.error \
			-i gtk-dialog-error "Can't store parcel data" \
			"Could not locate a suitable storage device for ISR parcel data.  Resuming a parcel is inadvisable."
		return
		;;
	esac
	notify-send -u low -c device -i gtk-harddisk -t 15000 "$short" "$long"
}

type=`detect`
if [ "$1" = "-q" ] ; then
	echo "$type"
elif [ -n "$1" ] ; then
	echo "Usage: $0 [-q]"
	exit 1
else
	notify "$type"
fi
exit 0
