#!/bin/bash
#
# early-scratch-setup: Set up scratch volume with /home and swap
#
# chkconfig: 345 00 99
# description: Set up scratch volume with /home and swap for live image.
#
# Copyright (C) 2010 Carnegie Mellon University
#
# This program is free software; you can redistribute it and/or modify it
# under the terms of version 2 of the GNU General Public License as published
# by the Free Software Foundation.  A copy of the GNU General Public License
# should have been distributed along with this program in the file
# COPYING.
#
# This program is distributed in the hope that it will be useful, but
# WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY
# or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public License
# for more details.
#

. /etc/init.d/functions

set -e

# cmdline_option, default
get_arg()  {
	for arg in `cat /proc/cmdline` ; do
		if [ "${arg##$1=}" != "$arg" ] ; then
			echo "${arg##$1=}"
			return
		fi
	done
	echo "$2"
}

if [ "$1" != "start" ] || ! strstr "`cat /proc/cmdline`" scratch_volume ; then
	exit 0
fi

# MiB
swap_size=`get_arg swap_size 2048`
# Minimum size (MiB)
store_size=`get_arg scratch_size $(($swap_size + 128))`
# KiB
min_extent_size=`get_arg min_extent_size 4096`

echo "Setting up scratch volume on local disk..."

# Create a DM volume containing all available free space
excludeargs="-x /dev/mapper/live-osimg-min -x /dev/mapper/live-rw
		-x `readlink -f /dev/live`"
for dev in /dev/loop*; do
	excludeargs="$excludeargs -x $dev"
done
/usr/sbin/gather_free_space -m "$store_size" -e "$min_extent_size" \
	-r /var/lib/transient-storage-info live-scratch-store $excludeargs

# Create an encrypted DM volume on top of it
cryptsetup create live-scratch-pv -c aes-xts-plain -d /dev/urandom \
	/dev/mapper/live-scratch-store

# Create an LVM volume group on that
pvcreate /dev/mapper/live-scratch-pv >/dev/null
vgcreate live-scratch /dev/mapper/live-scratch-pv >/dev/null

# Create swap and home partitions inside that
lvcreate -n swap -L "${swap_size}M" live-scratch >/dev/null
lvcreate -n home -l "100%FREE" live-scratch >/dev/null

# Format and mount home partition
/sbin/mkfs.ext4 -q -E lazy_itable_init=1 /dev/live-scratch/home
mount /dev/live-scratch/home /home

# Format and enable swap.  We use this to make the boot device hot-pluggable
# without implementing a Dracut hook to copy the live image to the scratch
# device: we just boot with the existing live_ram option, which reads the
# squashfs into tmpfs, then we let tmpfs swap the data if necessary.
mkswap -f /dev/live-scratch/swap >/dev/null
swapon /dev/live-scratch/swap
